spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch?autoReconnect=true
    username: batch
    password: qwe1212!Q
  batch:
    initialize-schema: always
    schema: classpath:/org/springframework/batch/core/schema-mysql.sql